/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AgeGroup = IDL.Variant({
  'ages3to5' : IDL.Null,
  'ages6to8' : IDL.Null,
  'allAges' : IDL.Null,
  'ages9to12' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EducationalModule = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'contentType' : IDL.Text,
  'learningItems' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const Game = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'gameType' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const Poem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'ageGroup' : AgeGroup,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'readingTime' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'ageGroup' : AgeGroup,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEducationalModule' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addGame' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'addPoem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AgeGroup, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'addStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AgeGroup, IDL.Nat, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEducationalModule' : IDL.Func([IDL.Nat], [], []),
  'deleteGame' : IDL.Func([IDL.Nat], [], []),
  'deletePoem' : IDL.Func([IDL.Nat], [], []),
  'deleteStory' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEducationalModule' : IDL.Func([IDL.Nat], [EducationalModule], ['query']),
  'getGame' : IDL.Func([IDL.Nat], [Game], ['query']),
  'getPoem' : IDL.Func([IDL.Nat], [Poem], ['query']),
  'getStory' : IDL.Func([IDL.Nat], [Story], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEducationalModules' : IDL.Func(
      [],
      [IDL.Vec(EducationalModule)],
      ['query'],
    ),
  'listGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'listPoems' : IDL.Func([], [IDL.Vec(Poem)], ['query']),
  'listPoemsByAgeGroup' : IDL.Func([AgeGroup], [IDL.Vec(Poem)], ['query']),
  'listStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'listStoriesByAgeGroup' : IDL.Func([AgeGroup], [IDL.Vec(Story)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEducationalModule' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateGame' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updatePoem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, AgeGroup, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateStory' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AgeGroup,
        IDL.Nat,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AgeGroup = IDL.Variant({
    'ages3to5' : IDL.Null,
    'ages6to8' : IDL.Null,
    'allAges' : IDL.Null,
    'ages9to12' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EducationalModule = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'contentType' : IDL.Text,
    'learningItems' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'gameType' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Poem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'ageGroup' : AgeGroup,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'readingTime' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'ageGroup' : AgeGroup,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEducationalModule' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addGame' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'addPoem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, AgeGroup, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'addStory' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AgeGroup,
          IDL.Nat,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEducationalModule' : IDL.Func([IDL.Nat], [], []),
    'deleteGame' : IDL.Func([IDL.Nat], [], []),
    'deletePoem' : IDL.Func([IDL.Nat], [], []),
    'deleteStory' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEducationalModule' : IDL.Func(
        [IDL.Nat],
        [EducationalModule],
        ['query'],
      ),
    'getGame' : IDL.Func([IDL.Nat], [Game], ['query']),
    'getPoem' : IDL.Func([IDL.Nat], [Poem], ['query']),
    'getStory' : IDL.Func([IDL.Nat], [Story], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEducationalModules' : IDL.Func(
        [],
        [IDL.Vec(EducationalModule)],
        ['query'],
      ),
    'listGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'listPoems' : IDL.Func([], [IDL.Vec(Poem)], ['query']),
    'listPoemsByAgeGroup' : IDL.Func([AgeGroup], [IDL.Vec(Poem)], ['query']),
    'listStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'listStoriesByAgeGroup' : IDL.Func([AgeGroup], [IDL.Vec(Story)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEducationalModule' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateGame' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updatePoem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AgeGroup,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateStory' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AgeGroup,
          IDL.Nat,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };