/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeGroup = { 'ages3to5' : null } |
  { 'ages6to8' : null } |
  { 'allAges' : null } |
  { 'ages9to12' : null };
export interface EducationalModule {
  'id' : bigint,
  'title' : string,
  'contentType' : string,
  'learningItems' : Array<string>,
  'description' : string,
}
export type ExternalBlob = Uint8Array;
export interface Game {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'gameType' : string,
  'image' : [] | [ExternalBlob],
}
export interface Poem {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : string,
  'image' : [] | [ExternalBlob],
  'ageGroup' : AgeGroup,
}
export interface Story {
  'id' : bigint,
  'title' : string,
  'readingTime' : bigint,
  'content' : string,
  'author' : string,
  'coverImage' : [] | [ExternalBlob],
  'ageGroup' : AgeGroup,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEducationalModule' : ActorMethod<
    [string, string, string, Array<string>],
    bigint
  >,
  'addGame' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'addPoem' : ActorMethod<
    [string, string, string, AgeGroup, [] | [ExternalBlob]],
    bigint
  >,
  'addStory' : ActorMethod<
    [string, string, string, AgeGroup, bigint, [] | [ExternalBlob]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEducationalModule' : ActorMethod<[bigint], undefined>,
  'deleteGame' : ActorMethod<[bigint], undefined>,
  'deletePoem' : ActorMethod<[bigint], undefined>,
  'deleteStory' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEducationalModule' : ActorMethod<[bigint], EducationalModule>,
  'getGame' : ActorMethod<[bigint], Game>,
  'getPoem' : ActorMethod<[bigint], Poem>,
  'getStory' : ActorMethod<[bigint], Story>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEducationalModules' : ActorMethod<[], Array<EducationalModule>>,
  'listGames' : ActorMethod<[], Array<Game>>,
  'listPoems' : ActorMethod<[], Array<Poem>>,
  'listPoemsByAgeGroup' : ActorMethod<[AgeGroup], Array<Poem>>,
  'listStories' : ActorMethod<[], Array<Story>>,
  'listStoriesByAgeGroup' : ActorMethod<[AgeGroup], Array<Story>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEducationalModule' : ActorMethod<
    [bigint, string, string, string, Array<string>],
    undefined
  >,
  'updateGame' : ActorMethod<
    [bigint, string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'updatePoem' : ActorMethod<
    [bigint, string, string, string, AgeGroup, [] | [ExternalBlob]],
    undefined
  >,
  'updateStory' : ActorMethod<
    [bigint, string, string, string, AgeGroup, bigint, [] | [ExternalBlob]],
    undefined
  >,
  'uploadImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];